# Use root/example as user/password credentials
version: '3.7'
 
services:
 
 db:
   image: mysql:8
   volumes:
     - type: bind
       source: ../mysql-db
       target: /var/lib/mysql
   environment:
     MYSQL_USER: node_user
     MYSQL_PASSWORD: l3tm31n
     MYSQL_DATABASE: testdb
     MYSQL_ROOT_PASSWORD: RootPass
   command: --default-authentication-plugin=mysql_native_password
   ports:
     - 3306:3306
 
 adminer:
   image: adminer
   restart: always
   ports:
     - 8000:8080
